name: Semgrep Scan

on:
  push:
    branches:
      - master

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Change this to your Python version

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config=p/security-audit --json . || true > semgrep_results.json

      - name: Upload results to GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep_results.json
